import { t } from '@lingui/macro'
import { useLingui } from '@lingui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  const { i18n } = useLingui()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          {i18n._(t`test`)}
          {i18n.locale}
        </h1>
      </main>
    </div>
  )
}

export default Home
